// import { Timekeeping } from "src/routes/mobile/timekeepings/entities/timekeeping.entity";

export const Constants = {
    databaseConnection: 'DATABASE_CONNECTION',
    userMobileReposistory: 'USER_MOBILE_REPOSISTORY',
    addressReposistory:'ADDRESS_REPOSISTORY',
    provinceReposistory: 'PROVINCE_REPOSISTORY',
    notificationReposistory: 'NOTIFICATION_REPOSISTORY',
    userDashboardReposistory:'USER_DASHBOARD_REPOSISTORY',
    flowerDashboardReposistory:'FLOWER_DASHBOARD_REPOSISTORY',
    flowerMobileReposistory:'FLOWER_MOBILE_REPOSISTORY',
    orderMobileReposistory: 'ORDER_MOBILE_REPOSISTORY',
    orderDashboardReposistory:'ORDER_DASHBOARD_REPOSISTORY',
    flowerTypeReposistory: 'FLOWER_TYPE_REPOSISTORY',
    databaseConnection2: 'DATABASE_CONNECTION_2',
    promotionReposistory:'PROMOTION_REPOSISTORY',
  
    tenantReposistory: 'TENANT_REPOSISTORY',
    roleReposistory: 'ROLE_REPOSISTORY',
    lineReposistory: 'LINE_REPOSISTORY',
    inventoryReposistory: 'INVENTORY_REPOSISTORY',
    lineMapReposistory: 'LINE_MAP_REPOSISTORY',
    lineMapMachineReposistory: 'LINE_MAP_MACHINE_REPOSISTORY',
    lineMapSewingStageReposistory: 'LINE_MAP_SEWING_STAGE_REPOSISTORY',
    actionReposistory: 'ACTION_TECHNIQUE_REPOSISTORY',
    articleReposistory: 'ARTICLE_REPOSISTORY',
    articleInStyleReposistory: 'ARTICLE_IN_STYLE_REPOSISTORY',
    resourceReposistory: 'RESOURCE_TECHNIQUE_REPOSISTORY',
    rolePermissionReposistory: 'ROLE_PERMISSION_TECHNIQUE_REPOSISTORY',
    permissionReposistory: 'PERMISSION_TECHNIQUE_REPOSISTORY',
    clientEnvironmentReposistory: 'CLIENT_ENVIRONMENT_REPOSISTORY',
    workerReposistory: 'WORKER_REPOSISTORY',
    workerRankReposistory: 'WORKER_RANK_REPOSISTORY',
    workerTechniqueReposistory: 'WORKER_TECHNIQUE_REPOSISTORY',
    styleGroupReposistory: 'STYLE_GROUP_REPOSISTORY',
    styleReposistory: 'STYLE_REPOSISTORY',
    supplierReposistory: 'SUPPLIER_REPOSISTORY',
    supplierContactReposistory: 'SUPPLIER_CONTACT_REPOSISTORY',
    orderReposistory: 'ORDER_REPOSISTORY',
    orderItemReposistory: 'ORDER_ITEM_REPOSISTORY',
    assignedOrderItemReposistory: 'ASSIGNED_ORDER_ITEM_REPOSISTORY',
    countryReposistory: 'COUNTRY_REPOSISTORY',
    customerReposistory: 'CUSTOMER_REPOSISTORY',
    customerContractReposistory: 'CUSTOMER_CONTRACT_REPOSISTORY',
    customerContactReposistory: 'CUSTOMER_CONTACT_REPOSISTORY',
    segmentReposistory: 'SEGMENT_REPOSISTORY',
    acceptanceCriteriaReposistory: 'ACCEPTANCE_CRITERIA_REPOSISTORY',
    defectCauseReposistory: 'DEFECT_CAUSE_REPOSISTORY',
    defectReposistory: 'DEFECT_REPOSISTORY',
    criteriaInSegmentReposistory: 'CRITERIA_IN_SEGMENT_REPOSISTORY',
    consumptionAdjustmentReposistory: 'CONSUMPTION_ADJUSTMENT_REPOSISTORY',
    segmentInStyleGroupReposistory: 'SEGMENT_IN_STYLEGROUP_REPOSISTORY',
    productionReportReposistory: 'PRODUCTION_REPORT_REPOSISTORY',
    qualityReportReposistory: 'QUALITY_REPORT_REPOSISTORY',
    colorReposistory: 'COLOR_REPOSISTORY',
    sizeReposistory: 'SIZE_REPOSISTORY',
    sewingEquipmentReposistory: 'SEWING_EQUIPMENT_REPOSISTORY',
    sewingStageClusterReposistory: 'SEWING_STAGE_CLUSTER_REPOSISTORY',
    sewingStageReposistory: 'SEWING_STAGE_REPOSISTORY',
    qcSamAdjustmentReposistory: 'QC_SAM_ADJUSTMENT_REPOSISTORY',
    dailyTargetReposistory: 'DAILY_TARGET_REPOSISTORY',
    dailyQcAggregateReposistory: 'DAILY_QC_AGGREGATE_REPOSISTORY',
    dailyQualityLineAggregateReposistory: 'DAILY_QUALITY_LINE_AGGREGATE_REPOSISTORY',
    qualityInspectionCheckpointReposistory: 'QUALITY_INSPECTION_CHECKPOINT_REPOSISTORY',
    dividedBundleReposistory: 'DIVIDED_BUNDLE_REPOSISTORY',
    workerProductivityAdjustmentReposistory: 'WORKER_PRODUCTIVITY_ADJUSTMENT_REPOSISTORY',

    //Mobile
    timekeepingReposistory: 'TIMEKEEPING_REPOSISTORY',
    dailyInspectionOrderReposistory: 'DAILY_INSPECTION_ORDER_REPOSISTORY',
    dailySewingOrderReposistory: 'DAILY_SEWING_ORDER_REPOSISTORY',
    dailyInspectionNoteReposistory: 'DAILY_INSPECTION_NOTE_REPOSISTORY',
    qualityInspectionStatusReposistory: 'QUALITY_INSPECTION_STATUS_REPOSISTORY',
    qualityInspectionStageReposistory: 'QUALITY_INSPECTION_STAGE_REPOSISTORY',
    defectCriteriaReposistory: 'DEFECT_CRITERIA_REPOSISTORY',
    styleCriteriaReposistory: 'STYLE_CRITERIA_REPOSISTORY',
    defectCriteriaDetailReposistory: 'DEFECT_CRITERIA_DETAIL_REPOSISTORY',
    sewingBundleCompletionReposistory: 'SEWING_BUNDLE_COMPLETION_REPOSISTORY',
};
